#!/bin/bash
### BEGIN INIT INFO
# Provides: iptables
# Required-Start: $local_fs $network
# Required-Stop: $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Firewall
# Description: Protect the computer against network attack
### END INIT INFO

# Script qui démarre les règles de filtrage IPv4
# Formation Debian GNU/Linux par Alexis de Lattre
# http://formation-debian.via.ecp.fr/
 
# iptables-restore(8) remet implicitement à zéro toutes les règles
 
# Les instructions qui suivent concernent la table « filter »,
# c'est à dire… le filtrage.
 
#########################
# Politiques par défaut #
#########################
# Les politiques par défaut déterminent le devenir d'un paquet auquel
# aucune règle spécifique ne s'applique.
 
# Les connexions entrantes sont bloquées par défaut
/sbin/iptables -P INPUT DROP
# Les connexions destinées à être routées sont acceptées par défaut
/sbin/iptables -P FORWARD DROP
# Les connexions sortantes sont acceptées par défaut
/sbin/iptables -P OUTPUT ACCEPT
 
######################
# Règles de filtrage #
######################
# Nous précisons ici des règles spécifiques pour les paquets vérifiant
# certaines conditions.
 
# Pas de filtrage sur l'interface de "loopback"
/sbin/iptables -A INPUT -i lo -j ACCEPT
 
# Accepter le protocole ICMP (notamment le ping)
/sbin/iptables -A INPUT -p icmp -j ACCEPT
 
# Accepter le protocole IGMP (pour le multicast)
/sbin/iptables -A INPUT -p igmp -j ACCEPT
 
# Accepter les packets entrants relatifs à des connexions déjà
# établies : cela va plus vite que de devoir réexaminer toutes
# les règles pour chaque paquet.
/sbin/iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
 
# Décommentez la ligne suivante pour que le serveur SSH éventuel
# soit joignable de l'extérieur
# /sbin/iptables -A INPUT -p tcp --dport ssh -j ACCEPT

# Décommentez la ligne suivante pour que le serveur SSH éventuel
# soit joignable de l'extérieur
# /sbin/iptables -A INPUT -p tcp --dport sftp -j ACCEPT
  
# Décommentez la ligne suivante pour que le serveur NFS éventuel
# soit joignable de l'interieur
# /sbin/iptables -A INPUT -s 192.168.1.0/24 -p tcp --dport nfs -j ACCEPT
# /sbin/iptables -A INPUT -s 192.168.1.0/24 -p udp --dport nfs -j ACCEPT
 
# Décommentez les lignes suivantes pour que le serveur de courrier
# éventuel soit joignable de l'extérieur.
# /sbin/iptables -A INPUT -p tcp --dports smtp -j ACCEPT
# Si vous avez activé les services SMTPS et soumission de messages…
# /sbin/iptables -A INPUT -p tcp --dports smtps -j ACCEPT
# /sbin/iptables -A INPUT -p tcp --dports submission -j ACCEPT
 
# Décommentez les deux lignes suivantes pour que le serveur de noms
# éventuel soit joignable de l'extérieur.
# /sbin/iptables -A INPUT -p tcp --dport domain -j ACCEPT
# /sbin/iptables -A INPUT -p udp --dport domain -j ACCEPT
 
# Décommentez la ligne suivante pour que le serveur Web éventuel
# soit joignable de l'extérieur.
# /sbin/iptables -A INPUT -p tcp --dport http -j ACCEPT
# Si vous avez activé le HTTPS…
# /sbin/iptables -A INPUT -p tcp --dport https -j ACCEPT

# Décommentez la ligne suivante pour que le serveur SVN éventuel
# soit joignable de l'extérieur.
# /sbin/iptables -A INPUT -p tcp --dport svn -j ACCEPT
 
# Décommentez les deux lignes suivantes pour que le serveur d'impression
# éventuel soit joignable de l'extérieur.
# /sbin/iptables -A INPUT -p tcp --dport ipp -j ACCEPT
# /sbin/iptables -A INPUT -p udp --dport ipp -j ACCEPT

# Décommentez les deux lignes suivantes pour que le serveur NetBIOS Name Service
# éventuel soit joignable de l'extérieur.
# /sbin/iptables -A INPUT -p udp --dport netbios-ns -j ACCEPT

# Décommentez les deux lignes suivantes pour que le serveur NetBIOS Datagram Service
# éventuel soit joignable de l'extérieur.
# /sbin/iptables -A INPUT -p udp --dport netbios-dgm -j ACCEPT
 
# Décommentez les deux lignes suivantes pour que le serveur Samba
# éventuel soit joignable de l'extérieur.
# /sbin/iptables -A INPUT -p tcp --dport netbios-ssn -j ACCEPT
# /sbin/iptables -A INPUT -p udp --dport netbios-ssn -j ACCEPT
 
# Décommentez la ligne suivante pour que des clients puissent se connecter
# à l'ordinateur par XDMCP.
# /sbin/iptables -A INPUT -p udp --dport xdmcp -j ACCEPT
 
# Décommentez la ligne suivante pour que l'ordinateur puisse se connecter
# par XDMCP à une machine distante).
# /sbin/iptables -A INPUT -p tcp --dport x11-1 -j ACCEPT
 
# Décommentez la ligne suivante pour pouvoir recevoir des flux VideoLAN.
# /sbin/iptables -A INPUT -p udp --dport 1234 -j ACCEPT
 
# Décommentez la ligne suivante pour pouvoir recevoir des annonces SAP
# (ce sont des annonces de session multicast).
# /sbin/iptables -A INPUT -p udp -d 224.2.127.254 --dport 9875 -j ACCEPT
 
# Décommentez les 3 lignes suivantes pour pouvoir utiliser GnomeMeeting
# /sbin/iptables -A INPUT -p tcp --dport 30000:33000 -j ACCEPT
# /sbin/iptables -A INPUT -p tcp --dport 1720 -j ACCEPT
# /sbin/iptables -A INPUT -p udp --dport 5000:5006 -j ACCEPT
 
# Décommentez la ligne suivante pour pouvoir partager de la musique par
# DAAP.
# /sbin/iptables -A INPUT -p tcp --dport daap -j ACCEPT
 
# Décommentez la ligne suivante pour que votre ordinateur
# annonce son nom et ses services par mDNS sur le réseau local (cela
# permet de le contacter sous « son nom d'hôte ».local).
# /sbin/iptables -A INPUT -p udp -d 224.0.0.251 --dport mdns -j ACCEPT
 
# Décommentez la ligne suivante pour que votre ordinateur accepte les
# demandes ssdp (Simple Service Discovery Protocol)
# permet de le contacter sous « son nom d'hôte ».local).
# /sbin/iptables -A INPUT -p udp -s 192.168.1.0/24 -d 239.255.255.250 --dport 1900 -j ACCEPT
 
# Décommentez la ligne suivante pour que votre ordinateur accepte les
# demandes ssdp (Simple Service Discovery Protocol)
# permet de le contacter sous « son nom d'hôte ».local).
# /sbin/iptables -A INPUT -p udp -s 192.168.1.0/24 -d 239.255.255.250 --dport 3702 -j ACCEPT
 
# La règle par défaut pour la chaine INPUT devient REJECT (contrairement
# à DROP qui ignore les paquets, avec REJECT, l'expéditeur est averti
# du refus). Il n'est pas possible de mettre REJECT comme politique par
# défaut. Au passage, on note les paquets qui vont être jetés, ça peut
# toujours servir.
# /sbin/iptables -A INPUT -j LOG --log-prefix "paquet IPv4 inattendu "
# /sbin/iptables -A INPUT -j REJECT
 
# COMMIT
 
# Les instructions qui suivent concernent la table « nat ». nat
 
########################
# Partage de connexion #
########################
 
# Décommentez la ligne suivante pour que le système fasse office de
# routeur NAT et remplacez « eth0 » par le nom de l'interface
# connectée à Internet.
# /sbin/iptables -A POSTROUTING -o eth0 -j MASQUERADE
 
########################
# Redirections de port #
########################
 
# Décommentez la ligne suivante pour que les requêtes TCP reçues sur
# le port 80 de l'interface eth0 soient redirigées à la machine dont
# l'adresse IPv4 est 192.168.0.3 sur son port 80 (la réponse à la
# requête sera transférée au client).
# /sbin/iptables -A PREROUTING -i eth0 -p tcp --dport 80 -j DNAT --to-destination 192.168.0.3:80
 
# COMMIT
 
####################
# Problème de MTU… #
####################
 
# Les instructions qui suivent concernent la table « mangle », c'est
# à dire l'altération des paquets mangle
 
# Si la connexion que vous partagez est une connexion ADSL directement gérée
# par votre ordinateur, vous serez probablement confronté au fameux problème du
# MTU. En résumé, le problème vient du fait que le MTU de la liaison entre
# votre fournisseur d'accès et le serveur NAT est un petit peu inférieur au MTU
# de la liaison Ethernet qui relie le serveur NAT aux machines qui sont
# derrière le NAT. Pour résoudre ce problème, décommentez la ligne suivante et
# remplacez « eth0 » par le nom de l'interface connectée à Internet.
# /sbin/iptables -A FORWARD -p tcp --tcp-flags SYN,RST SYN -j TCPMSS -o eth0 --clamp-mss-to-pmtu
